/**
 * Fixture helpers — paths and metadata for the generated test images.
 * Import this in tests that need real JPEG files.
 *
 * Fixtures are generated by `npm run fixtures` (scripts/generate-fixtures.ts).
 * They live in tests/fixtures/images/ which is git-ignored.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const FIXTURES_DIR = path.join(__dirname, 'images');

export interface FixtureMeta {
  name: string;
  path: string;
  /** Unix timestamp in seconds embedded as EXIF */
  ts: number;
}

export const FIXTURES: FixtureMeta[] = [
  { name: 'red.jpg', path: path.join(FIXTURES_DIR, 'red.jpg'), ts: 1_700_000_000 },
  { name: 'green.jpg', path: path.join(FIXTURES_DIR, 'green.jpg'), ts: 1_700_001_000 },
  { name: 'blue.jpg', path: path.join(FIXTURES_DIR, 'blue.jpg'), ts: 1_700_002_000 },
  { name: 'white.jpg', path: path.join(FIXTURES_DIR, 'white.jpg'), ts: 1_700_003_000 },
  { name: 'dark.jpg', path: path.join(FIXTURES_DIR, 'dark.jpg'), ts: 1_700_004_000 },
  { name: 'yellow.jpg', path: path.join(FIXTURES_DIR, 'yellow.jpg'), ts: 1_700_005_000 },
];

export function fixturePath(name: string): string {
  return path.join(FIXTURES_DIR, name);
}
